import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ReactQueryProvider } from './ReactQueryProvider'
import Image from 'next/image'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Pokemon-app',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ReactQueryProvider>
      <html lang="en">
        <body className={inter.className}>
          <div>
            <nav className="bg-amber-300 px-2 sm:px-4 py-2.5 shadow fixed w-full z-50">
              <div className="container flex flex-wrap items-center justify-between">
                <Link href="/" className="flex items-center">
                  <Image src={'/logo.png'} className="h-12 mr-3 sm:h-9" alt="Pokemon Logo" width={100} height={100}/>
                  <span className="self-center text-2xl font-extrabold whitespace-nowrap text-amber-700">Pokémon App</span>
                </Link>
              </div>
            </nav>
            <aside className="w-52 fixed mt-14 h-full shadow" aria-label="Sidebar">
              <div className="overflow-y-auto py-4 px-3 bg-gray-50 h-full">
                <ul className="space-y-2 text-gray-600">
                  <li>
                    <Link href="/"
                      className="flex items-center p-2 text-base font-normal rounded-lg hover:bg-gray-100">
                      <span className="ml-3">List</span>
                    </Link>
                  </li>
                  <li>
                    <Link href="/myPokemon"
                      className="flex items-center p-2 text-base font-normal rounded-lg hover:bg-gray-100">
                      <span className="ml-3">My Pokémon</span>
                    </Link>
                  </li>
                </ul>
              </div>
            </aside>
            <section className="text-gray-600 body-font font-sans ml-56 pt-20 pr-6">
              <div
                className="absolute -z-10 inset-0 bg-center"></div>
              <div className="container p-6 mb-24 mx-auto bg-white/60 rounded-2xl shadow-2xl">
                {children}
              </div>
            </section>
          </div>
        </body>
      </html>
    </ReactQueryProvider>
  )
}
